version: '3'

services:

    app:
        container_name: transfer-microservice-app
        build:
            context: ./
            dockerfile: .setup/build/dev/Dockerfile
        volumes:
            - .:/var/www
            - ./.docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        networks:
            - app-network
        depends_on:
            - db
            - redis

    nginx:
        build: .docker/nginx
        container_name: transfer-microservice-nginx
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - app

    db:
        build: ./.docker/mysql
        container_name: transfer-microservice-db
        restart: always
        tty: true
        ports:
            - "33006:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
            - ./.docker/mysql:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_DATABASE=transfers
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - app-network

    rabbitmq:
      image: rabbitmq:3.8.16-management
      container_name: rabbitmq
      hostname: rabbitmq
      ports:
        - "5672:5672"
        - "15672:15672"
        - "15692:15692"
      environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
        - RABBITMQ_DEFAULT_VHOST=/
      networks:
        - app-network

    redis:
        image: redis:alpine
        container_name: transfer-microservice-redis
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
