openapi: 3.0.0
info:
  title: Transfer
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Local
  - url: transfer-microservice-api
    description: Stage
  - url: transfer-microservice-api
    description: Production
paths:
  /api/v1/users:
    post:
      tags:
        - default
      summary: Create user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: André Luiz da Silva
                email: andreluizmicro@gmail.com
                cpf: 111.400.590-65
                password: A@34Fddar48Y#
                user_type_id: 1
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/accounts:
    post:
      tags:
        - default
      summary: Create Account
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                user_id: 6
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/accounts/deposit/1:
    post:
      tags:
        - default
      summary: Deposit
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                value: 15000
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/transfers:
    post:
      tags:
        - default
      summary: Create Transfer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                value: 1000
                payer: 1
                payee: 3
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
